In [18]:
import pandas as pd


food_desert = pd.read_excel('../data/rawdata/fooddesert.xlsx', sheet_name='Food Access Research Atlas')

In [19]:
food_desert.head()

,CensusTract,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
0,1001020100,Alabama,Autauga,1,1912,693,0,0,0.000000,0,...,221,1622,217,14,0,14,45,44,26,112
1,1001020200,Alabama,Autauga,1,2170,743,0,181,0.083410,0,...,214,888,1217,5,0,5,55,75,87,202
2,1001020300,Alabama,Autauga,1,3373,1256,0,0,0.000000,0,...,439,2576,647,17,5,11,117,87,108,120
3,1001020400,Alabama,Autauga,1,4386,1722,0,0,0.000000,0,...,904,4086,193,18,4,11,74,85,19,82
4,1001020500,Alabama,Autauga,1,10766,4082,0,181,0.016812,0,...,1126,8666,1437,296,9,48,310,355,198,488

In [20]:
cols = food_desert.columns.tolist() # reran after index was reset
print(cols)

['CensusTract', 'State', 'County', 'Urban', 'POP2010', 'OHU2010', 'GroupQuartersFlag', 'NUMGQTRS', 'PCTGQTRS', 'LILATracts_1And10', 'LILATracts_halfAnd10', 'LILATracts_1And20', 'LILATracts_Vehicle', 'HUNVFlag', 'LowIncomeTracts', 'PovertyRate', 'MedianFamilyIncome', 'LA1and10', 'LAhalfand10', 'LA1and20', 'LATracts_half', 'LATracts1', 'LATracts10', 'LATracts20', 'LATractsVehicle_20', 'LAPOP1_10', 'LAPOP05_10', 'LAPOP1_20', 'LALOWI1_10', 'LALOWI05_10', 'LALOWI1_20', 'lapophalf', 'lapophalfshare', 'lalowihalf', 'lalowihalfshare', 'lakidshalf', 'lakidshalfshare', 'laseniorshalf', 'laseniorshalfshare', 'lawhitehalf', 'lawhitehalfshare', 'lablackhalf', 'lablackhalfshare', 'laasianhalf', 'laasianhalfshare', 'lanhopihalf', 'lanhopihalfshare', 'laaianhalf', 'laaianhalfshare', 'laomultirhalf', 'laomultirhalfshare', 'lahisphalf', 'lahisphalfshare', 'lahunvhalf', 'lahunvhalfshare', 'lasnaphalf', 'lasnaphalfshare', 'lapop1', 'lapop1share', 'lalowi1', 'lalowi1share', 'lakids1', 'lakids1share', 'laseniors1', 'laseniors1share', 'lawhite1', 'lawhite1share', 'lablack1', 'lablack1share', 'laasian1', 'laasian1share', 'lanhopi1', 'lanhopi1share', 'laaian1', 'laaian1share', 'laomultir1', 'laomultir1share', 'lahisp1', 'lahisp1share', 'lahunv1', 'lahunv1share', 'lasnap1', 'lasnap1share', 'lapop10', 'lapop10share', 'lalowi10', 'lalowi10share', 'lakids10', 'lakids10share', 'laseniors10', 'laseniors10share', 'lawhite10', 'lawhite10share', 'lablack10', 'lablack10share', 'laasian10', 'laasian10share', 'lanhopi10', 'lanhopi10share', 'laaian10', 'laaian10share', 'laomultir10', 'laomultir10share', 'lahisp10', 'lahisp10share', 'lahunv10', 'lahunv10share', 'lasnap10', 'lasnap10share', 'lapop20', 'lapop20share', 'lalowi20', 'lalowi20share', 'lakids20', 'lakids20share', 'laseniors20', 'laseniors20share', 'lawhite20', 'lawhite20share', 'lablack20', 'lablack20share', 'laasian20', 'laasian20share', 'lanhopi20', 'lanhopi20share', 'laaian20', 'laaian20share', 'laomultir20', 'laomultir20share', 'lahisp20', 'lahisp20share', 'lahunv20', 'lahunv20share', 'lasnap20', 'lasnap20share', 'TractLOWI', 'TractKids', 'TractSeniors', 'TractWhite', 'TractBlack', 'TractAsian', 'TractNHOPI', 'TractAIAN', 'TractOMultir', 'TractHispanic', 'TractHUNV', 'TractSNAP']

In [21]:
food_desert['CensusTract'].is_unique #no repeat FIPS

True

In [22]:
food_desert.set_index('CensusTract', inplace=True) # called once, needs to be silenced if cell ran twice. #index willl throw an error.
food_desert.head()

,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,LILATracts_halfAnd10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
CensusTract,,,,,,,,,,,,,,,,,,,,,
1001020100,Alabama,Autauga,1,1912,693,0,0,0.000000,0,0,...,221,1622,217,14,0,14,45,44,26,112
1001020200,Alabama,Autauga,1,2170,743,0,181,0.083410,0,0,...,214,888,1217,5,0,5,55,75,87,202
1001020300,Alabama,Autauga,1,3373,1256,0,0,0.000000,0,0,...,439,2576,647,17,5,11,117,87,108,120
1001020400,Alabama,Autauga,1,4386,1722,0,0,0.000000,0,0,...,904,4086,193,18,4,11,74,85,19,82
1001020500,Alabama,Autauga,1,10766,4082,0,181,0.016812,0,0,...,1126,8666,1437,296,9,48,310,355,198,488

In [24]:
food_desert.rename(columns = {'CensusTract':'FIPS'}, inplace=True)
food_desert.head()

,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,LILATracts_halfAnd10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
CensusTract,,,,,,,,,,,,,,,,,,,,,
1001020100,Alabama,Autauga,1,1912,693,0,0,0.000000,0,0,...,221,1622,217,14,0,14,45,44,26,112
1001020200,Alabama,Autauga,1,2170,743,0,181,0.083410,0,0,...,214,888,1217,5,0,5,55,75,87,202
1001020300,Alabama,Autauga,1,3373,1256,0,0,0.000000,0,0,...,439,2576,647,17,5,11,117,87,108,120
1001020400,Alabama,Autauga,1,4386,1722,0,0,0.000000,0,0,...,904,4086,193,18,4,11,74,85,19,82
1001020500,Alabama,Autauga,1,10766,4082,0,181,0.016812,0,0,...,1126,8666,1437,296,9,48,310,355,198,488

In [6]:
# food_desert.loc[1001020500] #calling directly to the FIPS

In [25]:
food_desert.get_dtype_counts()

float64    112
int64       32
object       2
dtype: int64

In [26]:
food_desert.isnull().sum() #they are all zero! yay

State                   0
County                  0
Urban                   0
POP2010                 0
OHU2010                 0
GroupQuartersFlag       0
NUMGQTRS                0
PCTGQTRS                0
LILATracts_1And10       0
LILATracts_halfAnd10    0
LILATracts_1And20       0
LILATracts_Vehicle      0
HUNVFlag                0
LowIncomeTracts         0
PovertyRate             0
MedianFamilyIncome      0
LA1and10                0
LAhalfand10             0
LA1and20                0
LATracts_half           0
LATracts1               0
LATracts10              0
LATracts20              0
LATractsVehicle_20      0
LAPOP1_10               0
LAPOP05_10              0
LAPOP1_20               0
LALOWI1_10              0
LALOWI05_10             0
LALOWI1_20              0
                       ..
lawhite20               0
lawhite20share          0
lablack20               0
lablack20share          0
laasian20               0
laasian20share          0
lanhopi20               0
lanhopi20share          0
laaian20                0
laaian20share           0
laomultir20             0
laomultir20share        0
lahisp20                0
lahisp20share           0
lahunv20                0
lahunv20share           0
lasnap20                0
lasnap20share           0
TractLOWI               0
TractKids               0
TractSeniors            0
TractWhite              0
TractBlack              0
TractAsian              0
TractNHOPI              0
TractAIAN               0
TractOMultir            0
TractHispanic           0
TractHUNV               0
TractSNAP               0
Length: 146, dtype: int64

In [28]:
cols = food_desert.columns.tolist() #update after drop
cols

['State',
 'County',
 'Urban',
 'POP2010',
 'OHU2010',
 'GroupQuartersFlag',
 'NUMGQTRS',
 'PCTGQTRS',
 'LILATracts_1And10',
 'LILATracts_halfAnd10',
 'LILATracts_1And20',
 'LILATracts_Vehicle',
 'HUNVFlag',
 'LowIncomeTracts',
 'PovertyRate',
 'MedianFamilyIncome',
 'LA1and10',
 'LAhalfand10',
 'LA1and20',
 'LATracts_half',
 'LATracts1',
 'LATracts10',
 'LATracts20',
 'LATractsVehicle_20',
 'LAPOP1_10',
 'LAPOP05_10',
 'LAPOP1_20',
 'LALOWI1_10',
 'LALOWI05_10',
 'LALOWI1_20',
 'lapophalf',
 'lapophalfshare',
 'lalowihalf',
 'lalowihalfshare',
 'lakidshalf',
 'lakidshalfshare',
 'laseniorshalf',
 'laseniorshalfshare',
 'lawhitehalf',
 'lawhitehalfshare',
 'lablackhalf',
 'lablackhalfshare',
 'laasianhalf',
 'laasianhalfshare',
 'lanhopihalf',
 'lanhopihalfshare',
 'laaianhalf',
 'laaianhalfshare',
 'laomultirhalf',
 'laomultirhalfshare',
 'lahisphalf',
 'lahisphalfshare',
 'lahunvhalf',
 'lahunvhalfshare',
 'lasnaphalf',
 'lasnaphalfshare',
 'lapop1',
 'lapop1share',
 'lalowi1',
 'lalowi1share',
 'lakids1',
 'lakids1share',
 'laseniors1',
 'laseniors1share',
 'lawhite1',
 'lawhite1share',
 'lablack1',
 'lablack1share',
 'laasian1',
 'laasian1share',
 'lanhopi1',
 'lanhopi1share',
 'laaian1',
 'laaian1share',
 'laomultir1',
 'laomultir1share',
 'lahisp1',
 'lahisp1share',
 'lahunv1',
 'lahunv1share',
 'lasnap1',
 'lasnap1share',
 'lapop10',
 'lapop10share',
 'lalowi10',
 'lalowi10share',
 'lakids10',
 'lakids10share',
 'laseniors10',
 'laseniors10share',
 'lawhite10',
 'lawhite10share',
 'lablack10',
 'lablack10share',
 'laasian10',
 'laasian10share',
 'lanhopi10',
 'lanhopi10share',
 'laaian10',
 'laaian10share',
 'laomultir10',
 'laomultir10share',
 'lahisp10',
 'lahisp10share',
 'lahunv10',
 'lahunv10share',
 'lasnap10',
 'lasnap10share',
 'lapop20',
 'lapop20share',
 'lalowi20',
 'lalowi20share',
 'lakids20',
 'lakids20share',
 'laseniors20',
 'laseniors20share',
 'lawhite20',
 'lawhite20share',
 'lablack20',
 'lablack20share',
 'laasian20',
 'laasian20share',
 'lanhopi20',
 'lanhopi20share',
 'laaian20',
 'laaian20share',
 'laomultir20',
 'laomultir20share',
 'lahisp20',
 'lahisp20share',
 'lahunv20',
 'lahunv20share',
 'lasnap20',
 'lasnap20share',
 'TractLOWI',
 'TractKids',
 'TractSeniors',
 'TractWhite',
 'TractBlack',
 'TractAsian',
 'TractNHOPI',
 'TractAIAN',
 'TractOMultir',
 'TractHispanic',
 'TractHUNV',
 'TractSNAP']

In [29]:
texas_food_desert = food_desert[food_desert['State'] == 'Texas']
texas_food_desert.head()

,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,LILATracts_halfAnd10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
CensusTract,,,,,,,,,,,,,,,,,,,,,
48001950100,Texas,Anderson,0,4685,1874,0,49,0.010459,0,0,...,912,4012,452,22,0,13,186,236,125,218
48001950401,Texas,Anderson,0,5422,77,1,5219,0.962560,0,0,...,24,1825,2266,21,0,5,1305,1324,5,0
48001950402,Texas,Anderson,0,7535,83,1,7315,0.970803,0,0,...,134,2591,3248,13,0,10,1673,1737,0,0
48001950500,Texas,Anderson,1,4377,1604,0,86,0.019648,1,1,...,627,2737,800,19,2,20,799,1389,66,288
48001950600,Texas,Anderson,1,6405,2253,0,96,0.014988,1,1,...,791,3831,1674,68,4,43,785,1253,194,412

In [31]:
texas_food_desert_harris = texas_food_desert[texas_food_desert['County'] == 'Harris']
texas_food_desert_harris.head()

,State,County,Urban,POP2010,OHU2010,GroupQuartersFlag,NUMGQTRS,PCTGQTRS,LILATracts_1And10,LILATracts_halfAnd10,...,TractSeniors,TractWhite,TractBlack,TractAsian,TractNHOPI,TractAIAN,TractOMultir,TractHispanic,TractHUNV,TractSNAP
CensusTract,,,,,,,,,,,,,,,,,,,,,
48201100000,Texas,Harris,1,4690,1737,0,2407,0.513220,0,0,...,159,2669,1068,137,1,25,790,1070,360,50
48201210100,Texas,Harris,1,9652,72,1,9551,0.989536,0,0,...,49,4515,4903,61,0,3,170,1788,5,0
48201210400,Texas,Harris,1,5328,1593,0,257,0.048236,0,1,...,455,2617,931,26,4,43,1707,4025,354,564
48201210500,Texas,Harris,1,4882,1504,0,61,0.012495,0,1,...,523,2532,558,11,0,30,1751,4096,291,458
48201210600,Texas,Harris,1,5497,2037,0,0,0.000000,0,1,...,725,3832,117,41,1,53,1453,4378,198,229

In [32]:
# XLSX has a sheet with information on all Columns. pd.read_clipboard on this sheet plus an added column on whether to keep or drop this column for our MVP.
tract_info = pd.read_clipboard()
tract_info.head()

  Keep?        Field                 LongName
0     y  CensusTract             Census tract
1     n        State                    State
2     n       County                   County
3     y        Urban              Urban tract
4     n      POP2010  Population, tract total

In [35]:
col_drop = tract_info[tract_info['Keep?'] == 'n']
list_col_drop = col_drop['Field'].to_list()
list_col_drop

['State',
 'County',
 'POP2010',
 'OHU2010',
 'GroupQuartersFlag',
 'NUMGQTRS',
 'PCTGQTRS',
 'LILATracts_1And10',
 'LILATracts_halfAnd10',
 'LILATracts_1And20',
 'LILATracts_Vehicle',
 'HUNVFlag',
 'LowIncomeTracts',
 'PovertyRate',
 'MedianFamilyIncome',
 'LA1and10',
 'LAhalfand10',
 'LA1and20',
 'LATractsVehicle_20',
 'LAPOP1_10',
 'LAPOP05_10',
 'LAPOP1_20',
 'LALOWI1_10',
 'LALOWI05_10',
 'LALOWI1_20',
 'lapophalf',
 'lapophalfshare',
 'lalowihalf',
 'lalowihalfshare',
 'lakidshalf',
 'lakidshalfshare',
 'laseniorshalf',
 'laseniorshalfshare',
 'lawhitehalf',
 'lawhitehalfshare',
 'lablackhalf',
 'lablackhalfshare',
 'laasianhalf',
 'laasianhalfshare',
 'lanhopihalf',
 'lanhopihalfshare',
 'laaianhalf',
 'laaianhalfshare',
 'laomultirhalf',
 'laomultirhalfshare',
 'lahisphalf',
 'lahisphalfshare',
 'lahunvhalf',
 'lahunvhalfshare',
 'lasnaphalf',
 'lasnaphalfshare',
 'lapop1',
 'lapop1share',
 'lalowi1',
 'lalowi1share',
 'lakids1',
 'lakids1share',
 'laseniors1',
 'laseniors1share',
 'lawhite1',
 'lawhite1share',
 'lablack1',
 'lablack1share',
 'laasian1',
 'laasian1share',
 'lanhopi1',
 'lanhopi1share',
 'laaian1',
 'laaian1share',
 'laomultir1',
 'laomultir1share',
 'lahisp1',
 'lahisp1share',
 'lahunv1',
 'lahunv1share',
 'lasnap1',
 'lasnap1share',
 'lapop10',
 'lapop10share',
 'lalowi10',
 'lalowi10share',
 'lakids10',
 'lakids10share',
 'laseniors10',
 'laseniors10share',
 'lawhite10',
 'lawhite10share',
 'lablack10',
 'lablack10share',
 'laasian10',
 'laasian10share',
 'lanhopi10',
 'lanhopi10share',
 'laaian10',
 'laaian10share',
 'laomultir10',
 'laomultir10share',
 'lahisp10',
 'lahisp10share',
 'lahunv10',
 'lahunv10share',
 'lasnap10',
 'lasnap10share',
 'lapop20',
 'lapop20share',
 'lalowi20',
 'lalowi20share',
 'lakids20',
 'lakids20share',
 'laseniors20',
 'laseniors20share',
 'lawhite20',
 'lawhite20share',
 'lablack20',
 'lablack20share',
 'laasian20',
 'laasian20share',
 'lanhopi20',
 'lanhopi20share',
 'laaian20',
 'laaian20share',
 'laomultir20',
 'laomultir20share',
 'lahisp20',
 'lahisp20share',
 'lahunv20',
 'lahunv20share',
 'lasnap20',
 'lasnap20share',
 'TractLOWI',
 'TractKids',
 'TractSeniors',
 'TractWhite',
 'TractBlack',
 'TractAsian',
 'TractNHOPI',
 'TractAIAN',
 'TractOMultir',
 'TractHispanic',
 'TractHUNV',
 'TractSNAP']

In [47]:
TX_Food_Desert_Data = texas_food_desert_harris.drop(columns = list_col_drop)
TX_Food_Desert_Data.reset_index(inplace=True)
TX_Food_Desert_Data.rename(columns = {'CensusTract':'FIPS'}, inplace = True) 
TX_Food_Desert_Data.set_index('FIPS', inplace=True)
TX_Food_Desert_Data

             Urban  LATracts_half  LATracts1  LATracts10  LATracts20
FIPS
48201100000      1              0          0           0           0
48201210100      1              1          0           0           0
48201210400      1              1          0           0           0
48201210500      1              1          0           0           0
48201210600      1              1          0           0           0
48201210700      1              0          0           0           0
48201210800      1              1          0           0           0
48201210900      1              0          0           0           0
48201211000      1              0          0           0           0
48201211100      1              1          1           0           0
48201211200      1              1          0           0           0
48201211300      1              1          1           0           0
48201211400      1              1          1           0           0
48201211500      1              1          1           0           0
48201211600      1              1          0           0           0
48201211700      1              1          1           0           0
48201211900      1              1          0           0           0
48201212300      1              1          0           0           0
48201212400      1              1          0           0           0
48201212500      1              1          1           0           0
48201220100      1              1          0           0           0
48201220200      1              1          0           0           0
48201220300      1              1          0           0           0
48201220400      1              0          0           0           0
48201220500      1              1          0           0           0
48201220600      1              1          0           0           0
48201220700      1              1          0           0           0
48201220800      1              0          0           0           0
48201220900      1              1          0           0           0
48201221000      1              1          0           0           0
...            ...            ...        ...         ...         ...
48201554301      1              1          0           0           0
48201554302      1              1          0           0           0
48201554401      1              1          1           0           0
48201554402      1              1          1           0           0
48201554403      1              1          1           0           0
48201554501      1              1          1           0           0
48201554502      1              1          0           0           0
48201554600      1              1          1           0           0
48201554700      1              1          0           0           0
48201554801      1              1          1           0           0
48201554802      1              1          1           0           0
48201554901      1              1          1           0           0
48201554902      1              1          1           0           0
48201554903      1              1          1           0           0
48201555000      1              1          1           0           0
48201555100      1              1          1           0           0
48201555200      1              1          1           0           0
48201555301      1              1          1           0           0
48201555302      1              1          1           0           0
48201555303      0              0          0           0           0
48201555401      1              1          1           0           0
48201555402      1              1          1           0           0
48201555501      0              0          0           0           0
48201555502      1              1          1           0           0
48201555600      0              0          0           0           0
48201555701      1              1          1           0           0
48201555702      1              1          1           0           0
48201556000      0              0          0           0           0
48201980000      1              1          1           0           0
48201980100      1              1          1           0           0

[786 rows x 5 columns]

In [75]:
from pathlib import Path

output_path = Path("../data/cleandata/food_desert.csv")

with open(output_path, 'w') as file:
    file.write(TX_Food_Desert_Data.to_csv())