In [25]:
# Import necessary libraries and dependencies
import pandas as pd
from pathlib import Path
%matplotlib inline

In [26]:
# Use the Pathlib libary to set the path to the CSV
csv_path = Path('../data/rawdata/eviction_data.csv')
df = pd.read_csv(csv_path)
df['GEOID'] = df['GEOID'].astype(str)
df.head()

,GEOID,year,name,parent-location,population,poverty-rate,renter-occupied-households,pct-renter-occupied,median-gross-rent,median-household-income,...,pct-nh-pi,pct-multiple,pct-other,eviction-filings,evictions,eviction-rate,eviction-filing-rate,low-flag,imputed,subbed
0,48,2000,Texas,USA,20851820.0,15.37,1115310.0,36.2,574.0,39927.0,...,0.05,1.11,0.1,49721.0,17661.0,1.58,4.46,1,0,0
1,48,2001,Texas,USA,20851820.0,15.37,2464458.0,36.2,574.0,39927.0,...,0.05,1.11,0.1,112368.0,56760.0,2.30,4.56,1,0,0
2,48,2002,Texas,USA,20851820.0,15.37,2536161.0,36.2,574.0,39927.0,...,0.05,1.11,0.1,134427.0,68911.0,2.72,5.30,1,0,0
3,48,2003,Texas,USA,20851820.0,15.37,2617527.0,36.2,574.0,39927.0,...,0.05,1.11,0.1,146145.0,74525.0,2.85,5.58,1,0,0
4,48,2004,Texas,USA,20851820.0,15.37,2707586.0,36.2,574.0,39927.0,...,0.05,1.11,0.1,153449.0,77650.0,2.87,5.67,1,0,0

In [27]:
#get columns list to drop unnecesary columns
list(df)

['GEOID',
 'year',
 'name',
 'parent-location',
 'population',
 'poverty-rate',
 'renter-occupied-households',
 'pct-renter-occupied',
 'median-gross-rent',
 'median-household-income',
 'median-property-value',
 'rent-burden',
 'pct-white',
 'pct-af-am',
 'pct-hispanic',
 'pct-am-ind',
 'pct-asian',
 'pct-nh-pi',
 'pct-multiple',
 'pct-other',
 'eviction-filings',
 'evictions',
 'eviction-rate',
 'eviction-filing-rate',
 'low-flag',
 'imputed',
 'subbed']

In [28]:
# Drop extraneous columns
df_data = df.drop(columns=[
     'rent-burden',
     'pct-white',
     'pct-af-am',
     'pct-hispanic',
     'pct-am-ind',
     'pct-asian',
     'pct-nh-pi',
     'pct-multiple',
     'pct-other',
     'low-flag',
     'imputed',
     'subbed'
])
df_data = df_data.dropna()
df_data.head()

,GEOID,year,name,parent-location,population,poverty-rate,renter-occupied-households,pct-renter-occupied,median-gross-rent,median-household-income,median-property-value,eviction-filings,evictions,eviction-rate,eviction-filing-rate
0,48,2000,Texas,USA,20851820.0,15.37,1115310.0,36.2,574.0,39927.0,82500.0,49721.0,17661.0,1.58,4.46
1,48,2001,Texas,USA,20851820.0,15.37,2464458.0,36.2,574.0,39927.0,82500.0,112368.0,56760.0,2.30,4.56
2,48,2002,Texas,USA,20851820.0,15.37,2536161.0,36.2,574.0,39927.0,82500.0,134427.0,68911.0,2.72,5.30
3,48,2003,Texas,USA,20851820.0,15.37,2617527.0,36.2,574.0,39927.0,82500.0,146145.0,74525.0,2.85,5.58
4,48,2004,Texas,USA,20851820.0,15.37,2707586.0,36.2,574.0,39927.0,82500.0,153449.0,77650.0,2.87,5.67

In [29]:
#view columns left
list(df_data)

['GEOID',
 'year',
 'name',
 'parent-location',
 'population',
 'poverty-rate',
 'renter-occupied-households',
 'pct-renter-occupied',
 'median-gross-rent',
 'median-household-income',
 'median-property-value',
 'eviction-filings',
 'evictions',
 'eviction-rate',
 'eviction-filing-rate']

In [30]:
#filter df by Harris County
df_filtered = df_data.loc[df_data['parent-location'] == "Harris County, Texas"]

#filter usign LEN >12 for the FIPS, this avoid duplication of values in data 
df_filtered = df_filtered[df_filtered['GEOID'].str.len()>11]
df_filtered.head()

,GEOID,year,name,parent-location,population,poverty-rate,renter-occupied-households,pct-renter-occupied,median-gross-rent,median-household-income,median-property-value,eviction-filings,evictions,eviction-rate,eviction-filing-rate
242568,482011000001,2001,1000.1,"Harris County, Texas",4904.00,67.64,265.0,94.47,282.0,7697.0,0.0,22.0,17.0,6.41,8.30
242569,482011000001,2002,1000.1,"Harris County, Texas",4904.00,67.64,291.0,94.47,282.0,7697.0,0.0,14.0,6.0,2.06,4.80
242570,482011000001,2003,1000.1,"Harris County, Texas",4904.00,67.64,318.0,94.47,282.0,7697.0,0.0,24.0,11.0,3.46,7.56
242571,482011000001,2004,1000.1,"Harris County, Texas",4904.00,67.64,344.0,94.47,282.0,7697.0,0.0,16.0,12.0,3.49,4.65
242572,482011000001,2005,1000.1,"Harris County, Texas",1504.69,0.00,370.0,90.31,367.0,10433.0,208300.0,1.0,1.0,0.27,0.27

In [31]:
#groupby to confirm population match 
df_year = df_filtered.groupby('year').sum()
df_year

,population,poverty-rate,renter-occupied-households,pct-renter-occupied,median-gross-rent,median-household-income,median-property-value,eviction-filings,evictions,eviction-rate,eviction-filing-rate
year,,,,,,,,,,,
2001,3400578.13,32196.84,546836.0,90606.23,1489135.50,1.028872e+08,2.176303e+08,22417.0,13717.0,5797.02,9386.07
2002,3400578.13,32196.84,554915.0,90606.23,1489135.50,1.028872e+08,2.176303e+08,23459.0,13569.0,5698.52,9630.57
2003,3400578.13,32196.84,563199.0,90606.23,1489135.50,1.028872e+08,2.176303e+08,25899.0,14446.0,5820.81,10247.24
2004,3400578.13,32196.84,571281.0,90606.23,1489135.50,1.028872e+08,2.176303e+08,27151.0,14284.0,5822.85,10605.75
2005,3909790.11,32107.13,579888.0,89583.52,1773670.16,1.220711e+08,3.122803e+08,28112.0,15295.0,6127.49,10873.56
2006,3909790.11,32107.13,587649.0,89583.52,1773670.16,1.220711e+08,3.122803e+08,29629.0,17504.0,7166.47,11758.85
2007,3909790.11,32107.13,595880.0,89583.52,1773670.16,1.220711e+08,3.122803e+08,29891.0,18097.0,7793.56,12419.15
2008,3909790.11,32107.13,604015.0,89583.52,1773670.16,1.220711e+08,3.122803e+08,28958.0,15551.0,6501.42,11383.17
2009,3909790.11,32107.13,612249.0,89583.52,1773670.16,1.220711e+08,3.122803e+08,51916.0,26838.0,10586.52,18937.74
2010,3516918.00,29102.41,514580.0,75230.15,1774256.00,1.017340e+08,2.741103e+08,48045.0,23889.0,9627.90,17828.08
2011,3469925.00,26435.34,486653.0,71358.32,1628232.00,9.039052e+07,2.500621e+08,42133.0,21003.0,7769.52,14051.40
2012,3469925.00,26435.34,500991.0,71358.32,1628232.00,9.039052e+07,2.500621e+08,41888.0,20065.0,7121.64,13517.51
2013,3469925.00,26435.34,515834.0,71358.32,1628232.00,9.039052e+07,2.500621e+08,43615.0,21347.0,7213.10,13677.05
2014,3469925.00,26435.34,529880.0,71358.32,1628232.00,9.039052e+07,2.500621e+08,42240.0,21692.0,7258.26,13175.75
2015,3469925.00,26435.34,544445.0,71358.32,1628232.00,9.039052e+07,2.500621e+08,38295.0,18753.0,6235.41,11691.64
2016,3469925.00,26435.34,558771.0,71358.32,1628232.00,9.039052e+07,2.500621e+08,26750.0,13286.0,4147.31,7723.21

In [32]:
df_filtered.rename(columns={"GEOID":'FIPS'}, inplace=True)
df_filtered.head()

,FIPS,year,name,parent-location,population,poverty-rate,renter-occupied-households,pct-renter-occupied,median-gross-rent,median-household-income,median-property-value,eviction-filings,evictions,eviction-rate,eviction-filing-rate
242568,482011000001,2001,1000.1,"Harris County, Texas",4904.00,67.64,265.0,94.47,282.0,7697.0,0.0,22.0,17.0,6.41,8.30
242569,482011000001,2002,1000.1,"Harris County, Texas",4904.00,67.64,291.0,94.47,282.0,7697.0,0.0,14.0,6.0,2.06,4.80
242570,482011000001,2003,1000.1,"Harris County, Texas",4904.00,67.64,318.0,94.47,282.0,7697.0,0.0,24.0,11.0,3.46,7.56
242571,482011000001,2004,1000.1,"Harris County, Texas",4904.00,67.64,344.0,94.47,282.0,7697.0,0.0,16.0,12.0,3.49,4.65
242572,482011000001,2005,1000.1,"Harris County, Texas",1504.69,0.00,370.0,90.31,367.0,10433.0,208300.0,1.0,1.0,0.27,0.27

In [33]:
#data frame to csvfile
df_filtered.to_csv(r'../data/cleandata/eviction_data.csv', index=False)